---

- name: Install the  SQL Database
  ansible.builtin.package:
    name:
      - mariadb-server
    state: present
  when: ansible_os_family == "Debian"

- name: Start and enable SQL service
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: yes

- name: Install etcd
  ansible.builtin.package:
    name: etcd-server
    state: present

- name: Start and enable etcd service
  ansible.builtin.service:
    name: etcd
    state: started
    enabled: yes
